language: go
gobuild_args: -v -tags ci

os:
  - linux
  - osx

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
- ./admin/setup_minio_test_environment.sh
- ./admin/setup_bftpd_test_environment.sh
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls

script:
- go test -v -tags ci ./...
- $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email:
    on_success: change
    on_failure: always
