language: go

os:
  - linux
  - osx

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install: ./integration_tests/setup_minio_test_environment.sh

notifications:
  email:
    on_success: change
    on_failure: always
